/*
 * This file is auto-generated by gen-weights.py
 */

#pragma once
#define KRN_ROWS	5
#define KRN_COLS	5

#define DIGITS 10

#define IMG_ROWS 28
#define IMG_COLS 28

// Padding.
#define	PAD_ROWS (KRN_ROWS - 1)
#define	PAD_COLS (KRN_COLS - 1)
#define PAD_IMG_ROWS (IMG_ROWS + PAD_ROWS)
#define PAD_IMG_COLS (IMG_COLS + PAD_COLS)

// Convolutional layer.
#define FILTERS1	20

#define CHANNELS1	1

#define CONV1_ROWS	28

#define CONV1_COLS	28

#define FILTERS2	50

#define CHANNELS2	20

#define CONV2_ROWS	10

#define CONV2_COLS	10

// Pool layer.
#define POOL_ROWS	2
#define POOL_COLS	2
#define POOL_IMG_ROWS1 (CONV1_ROWS / POOL_ROWS)
#define POOL_IMG_COLS1 (CONV1_COLS / POOL_COLS)
#define POOL_IMG_ROWS2 (CONV2_ROWS / POOL_ROWS)
#define POOL_IMG_COLS2 (CONV2_COLS / POOL_COLS)

// Fatten layer.
#define FLAT_SIZE (FILTERS2 * POOL_IMG_ROWS2 * POOL_IMG_COLS2)

// Dense layers.
#define DENSE_SIZE 10
